apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-multi-container
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-multi-container
  template:
    metadata:
      name: nginx-multi-container
      labels:
        name: nginx-multi-container
    spec:
      containers:
        - name: nginx-multi-container
          image: nginx
          ports:
            - containerPort: 80
        - name: nodejs-web
          image: khannedy/nodejs-web
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-multi-container
spec:
  selector:
    name: nginx-multi-container
  ports:
    - port: 8080
      targetPort: 80
      name: nginx-multi-container
    - port: 3000
      targetPort: 3000
      name: nodejs-web

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-multi-container
  labels:
    name: curl-multi-container
spec:
  containers:
    - name: curl-multi-container
      image: khannedy/nginx-curl
