apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-lb
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-lb
  template:
    metadata:
      name: nginx-lb
      labels:
        name: nginx-lb
    spec:
      containers:
        - name: nginx-lb
          image: nginx
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lb
spec:
  type: LoadBalancer
  selector:
    name: nginx-lb
  ports:
    - port: 80
      targetPort: 80
